### ISSUE TITLE
Question about training data.

### ISSUE THREAD

**Issue by ZongfangLiu** [PeterWang512/GenDataAttribution#3]
Hi, thanks for your amazing job! Your findings and methodologies have greatly impressed me and my team and your codes are well organized and really easy to read and understand. We are following your work now. We would like to know whether it's possible to access to the training set?  

Thank you for your time !

**Comment by PeterWang512** [comment]
Thanks for the inquiry. Since we are facing challenges in hosting the TB-scale training set without throttling by the cloud server (e.g., Google Drive has a rate limit), we currently will send dataset links upon request via email.
